package it.pagopa.pn.notificationcostservice.middleware.dao.dynamo.entity.notificationdeliverycost;

import it.pagopa.pn.notificationcostservice.middleware.dao.dynamo.entity.notificationdeliverycost.analogcost.FirstAnalogCostEntity;
import it.pagopa.pn.notificationcostservice.middleware.dao.dynamo.entity.notificationdeliverycost.analogcost.SecondAnalogCostEntity;
import it.pagopa.pn.notificationcostservice.middleware.dao.dynamo.entity.notificationdeliverycost.analogcost.SimpleRegisteredLetterCostEntity;
import it.pagopa.pn.notificationcostservice.model.notificationdeliverycost.NotificationFeePolicy;
import it.pagopa.pn.notificationcostservice.model.notificationdeliverycost.PagoPaIntMode;
import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@DynamoDbBean
@Getter
@Setter
public class NotificationDeliveryCostEntity {

    public static final String COL_PK = "pk";
    public static final String COL_SK = "sk";
    public static final String COL_RECIPIENT_INTERNAL_ID = "recipientInternalId";
    public static final String COL_SENDER_PA_ID = "senderPaId";
    public static final String COL_SENDER_TAX_ID = "senderTaxId";
    public static final String COL_BASE_COST = "baseCost";
    public static final String COL_FIRST_ANALOG_COST = "firstAnalogCost";
    public static final String COL_SECOND_ANALOG_COST = "secondAnalogCost";
    public static final String COL_SIMPLE_REGISTERED_LETTER_COST = "simpleRegisteredLetterCost";
    public static final String COL_IS_DELETED = "isDeleted";
    public static final String COL_SEND_FEE = "sendFee";
    public static final String COL_PA_FEE = "paFee";
    public static final String COL_NOTIFICATION_FEE_POLICY = "notificationFeePolicy";
    public static final String COL_PAGO_PA_INT_MODE = "pagoPaIntMode";
    public static final String COL_VAT = "vat";
    public static final String COL_LAST_UPDATE = "lastUpdate";

    private String iun;
    private Integer recIndex;
    private String recipientInternalId;
    private String senderPaId;
    private String senderTaxId;
    private BaseCostEntity baseCost;
    private FirstAnalogCostEntity firstAnalogCost;
    private SecondAnalogCostEntity secondAnalogCost;
    private SimpleRegisteredLetterCostEntity simpleRegisteredLetterCost;
    private Boolean isDeleted;
    private NotificationFeePolicy notificationFeePolicy;
    private PagoPaIntMode pagoPaIntMode;
    private Integer vat;
    private Instant lastUpdate;

    @DynamoDbPartitionKey
    @DynamoDbAttribute(COL_PK)
    public String getIun() {
        return iun;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute(COL_SK)
    public Integer getRecIndex() {
        return recIndex;
    }

    @DynamoDbAttribute(COL_RECIPIENT_INTERNAL_ID)
    public String getRecipientInternalId() {
        return recipientInternalId;
    }

    @DynamoDbAttribute(COL_SENDER_PA_ID)
    public String getSenderPaId() {
        return senderPaId;
    }

    @DynamoDbAttribute(COL_SENDER_TAX_ID)
    public String getSenderTaxId() {
        return senderTaxId;
    }

    @DynamoDbAttribute(COL_BASE_COST)
    public BaseCostEntity getBaseCost() {
        return baseCost;
    }

    @DynamoDbAttribute(COL_FIRST_ANALOG_COST)
    public FirstAnalogCostEntity getFirstAnalogCost() {
        return firstAnalogCost;
    }

    @DynamoDbAttribute(COL_SECOND_ANALOG_COST)
    public SecondAnalogCostEntity getSecondAnalogCost() {
        return secondAnalogCost;
    }

    @DynamoDbAttribute(COL_SIMPLE_REGISTERED_LETTER_COST)
    public SimpleRegisteredLetterCostEntity getSimpleRegisteredLetterCost() {
        return simpleRegisteredLetterCost;
    }

    @DynamoDbAttribute(COL_IS_DELETED)
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    @DynamoDbAttribute(COL_NOTIFICATION_FEE_POLICY)
    public NotificationFeePolicy getNotificationFeePolicy() {
        return notificationFeePolicy;
    }

    @DynamoDbAttribute(COL_PAGO_PA_INT_MODE)
    public PagoPaIntMode getPagoPaIntMode() {
        return pagoPaIntMode;
    }

    @DynamoDbAttribute(COL_VAT)
    public Integer getVat() {
        return vat;
    }

    @DynamoDbAttribute(COL_LAST_UPDATE)
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getLastUpdate() {
        return lastUpdate;
    }
}
