package it.pagopa.pn.notificationcostservice.config.springbootcfg;

import it.pagopa.pn.commons.configs.RuntimeMode;
import it.pagopa.pn.commons.configs.aws.AwsConfigs;
import it.pagopa.pn.commons.configs.aws.AwsServicesClientsConfig;
import it.pagopa.pn.commons.utils.dynamodb.async.DynamoDbEnhancedAsyncClientDecorator;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient;

@Configuration
public class AwsServicesClientsConfigActivation extends AwsServicesClientsConfig {

    public AwsServicesClientsConfigActivation(AwsConfigs props) {
        super(props, RuntimeMode.PROD);
    }
    /*Questo bean è duplicato per aggiungere le logiche delle estensioni*/
    @Bean @Primary
    public DynamoDbEnhancedAsyncClient dynamoDbEnhancedAsyncClientWithMDC(DynamoDbAsyncClient delegate) {
        return new DynamoDbEnhancedAsyncClientDecorator(this.dynamoDbEnhancedAsyncClient(delegate));
    }

    private DynamoDbEnhancedAsyncClient dynamoDbEnhancedAsyncClient(DynamoDbAsyncClient baseAsyncClient) {
        return DynamoDbEnhancedAsyncClient.builder()
                .dynamoDbClient(baseAsyncClient)
                .extensions(AutoGeneratedTimestampRecordExtension.create())
                .build();
    }
}
