openapi: 3.0.3
info:
  termsOfService: https://da-definire/
  title: 'API di notification cost service'
  x-summary: 'API di  notification cost service'
  x-api-id: api-internal-pn-notification-cost-service
  version: '1.0.0'
  description: >-
    Da fare
paths:
  "/notification-cost-private/cost/{iun}/recipient/{recIndex}":
    get:
      operationId: NotificationCostRecipient                                     # ONLY EXTERNAL
      summary: Retrieve notification cost for recipient
      description: >-
        Servizio che restituisce il costo di notificazione per il singolo destinatario
      tags:
        - NotificationCostRecipient
      parameters:
        - name: iun
          in: path
          required: true
          description: Identificativo Univoco Notifica (IUN)
          schema:
            type: string
          example: '00000000-0000-0000-0000-000000000000'
        - name: recIndex
          in: path
          required: true
          description: Index destinatario notifica digitale
          schema:
            type: integer
            format: int32
          example: 0
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationCostRecipientResponse'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'


components:
  
  schemas:
    NotificationCostRecipientResponse:
      title: Notification cost Response for recipient
      description: >-
        Notification cost and effective date
      type: object
      properties:
        totalCost:
          $ref: '#/components/schemas/TotalCost'
        pagoPaIntMode:
          type: string
          description: >-
            Modalitá di integrazione pagoPA per l'attualizazione del costo della notifica. <br/>
            - _NONE_: nessuna attualizzazione. <br/>
            - _SYNC_: modalitá sincrona. <br/>
            - _ASYNC_: modalitá asincrona. <br/>
          enum:
            - NONE
            - SYNC
            - ASYNC
    
    TotalCost:
      title: Costo di notificazione applicato al destinatario
      description: >-
        Costo di notificazione applicato al destinatario
      type: object
      properties:
        cost:
          description: Costo totale in eurocent
          type: integer
          format: int32
        details:
          $ref: '#/components/schemas/TotalCostDetails'
    
    TotalCostDetails:
      title: Dettaglio del costo totale per il destinatario
      description: >-
        Dettaglio dei singoli componenti che compongono il costo di notificazione applicato al destinatario
      type: object
      properties:
        baseCost:
          $ref: '#/components/schemas/BaseCost'
        firstAnalogCost:
          $ref: '#/components/schemas/AnalogCost'
        secondAnalogCost:
          $ref: '#/components/schemas/AnalogCost'
        simpleRegisteredLetterCost:
          $ref: '#/components/schemas/AnalogCost'
        vat:
          type: integer
          description: >-
            IVA espressa in percentuale sui costi degli avvisi in formato cartaceo.<br/>
            Esempio vat al 22% -> 22 <br/>
          format: int32
          minimum: 0
          maximum: 100
        notificationFeePolicy:
          type: string
          description: >-
            Politica di addebitamento dei costi di notifica. <br/>
            - _FLAT_RATE_: costo forfettario fisso. In questa modalità SEND non gestisce
            il costo della notifica per il destinatario.<br/>
            - _DELIVERY_MODE_: costo calcolato in base all'effettivo percorso di notifica. <br/>
          enum:
            - FLAT_RATE
            - DELIVERY_MODE
    
    BaseCost:
      title: Costo base di notificazione
      description: >-
        Costo base di notificazione
      type: object
      properties:
        cost:
          description: Costo base di notificazione in eurocent
          type: integer
          format: int32
        details:
          $ref: '#/components/schemas/BaseCostDetails'
    
    BaseCostDetails:
      title: Dettaglio del costo base di notificazione
      description: >-
        Dettaglio dei singoli componenti che compongono il costo base di notificazione
      type: object
      properties:
        paFee:
          type: integer
          description: >-
            Costo espresso in eurocent sostenuto dal mittente
            Esempio paFee ad 1€ -> 100 <br/>
          format: int32
          minimum: 0
          maximum: 100
        sendFee:
          description: costo base di SeND per notificazione
          type: integer
          format: int32
    
    AnalogCost:
      title: Costo di invio cartaceo
      description: >-
        Costo del singolo invio cartaceo compreso di iva (vat), con il dettaglio sul tipo di prodotto
      type: object
      properties:
        cost:
          description: Costo invio cartaceo in eurocent compreso di iva (vat)
          type: integer
          format: int32
        productType:
          type: string
          maxLength: 10
          description: >
            Tipo di invio cartaceo effettivamente inviato
              - __AR__: Raccomandata nazionale Andata e Ritorno
              - __890__: Recapito a norma della legge 890/1982
              - __RIR__: Raccomandata internazionale Andata e Ritorno
              - __RS__: Raccomandata nazionale Semplice
              - __RIS__: Raccomandata internazionale Semplice
    
    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'
    ProblemError:
      $ref: './remote-refs.yaml#/components/schemas/ProblemError'