logging.config=classpath:logback.xml
spring.output.ansi.enabled=never

pn.env.runtime=PROD
spring.application.name=pn-notification-cost-service

management.endpoints.web.exposure.include=health,metrics,loggers