AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  AlarmSNSTopicName:
    Type: String
    Description: ''

  #Log
  LogRetention:
    Type: Number
    Default: 14
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  #DynamoDB tables
  NotificationDeliveryCostTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-NotificationDeliveryCost'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaymentInfoTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaymentInfo'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  #Sqs queues
  PnNotificationCostToUpdateQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-notification-cost-to-update'
        HasDLQ: "true"
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
  #Log Group
  PnNotificationCostServiceLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-notification-cost-service'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  CostEventUpdateLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-cost-event-update"
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:
  CostEventUpdateLambdaName:
    Value: !Sub "${ProjectName}-cost-event-update"

  # DynamoDB tables
  NotificationDeliveryCostTableName:
    Description: Name of dynamodb table containing cost of notification delivery
    Value: !Ref NotificationDeliveryCostTable
  
  NotificationDeliveryCostTableArn:
    Description: ARN of dynamodb table containing cost of notification delivery
    Value: !Sub '${NotificationDeliveryCostTable.Arn}'

  PaymentInfoTableName:
    Description: Name of dynamodb table containing info about payments
    Value: !Ref PaymentInfoTable

  PaymentInfoTableArn:
    Description: ARN of dynamodb table containing info about payments
    Value: !Sub '${PaymentInfoTable.Arn}'
  # Log group exports
  EcsNotificationCostServiceLogGroup:
    Value: !GetAtt PnNotificationCostServiceLogGroup.Outputs.LogGroupName
  # Sqs
  PnNotificationCostToUpdateQueueName:
    Value: !GetAtt PnNotificationCostToUpdateQueue.Outputs.QueueName
    Description: pn-Notification-Cost-To-Update queue name
  PnNotificationCostToUpdateQueueURL:
    Value: !GetAtt PnNotificationCostToUpdateQueue.Outputs.QueueURL
    Description: pn-Notification-Cost-To-Update queue URL
  PnNotificationCostToUpdateQueueARN:
    Value: !GetAtt PnNotificationCostToUpdateQueue.Outputs.QueueARN
    Description: pn-Notification-Cost-To-Update queue ARN
  PnNotificationCostToUpdateQueueAlarmARN:
    Value: !GetAtt PnNotificationCostToUpdateQueue.Outputs.SqsDLQAlarmArn
    Description: pn-Notification-Cost-To-Update alarm ARN
  PnNotificationCostToUpdateQueueAgeAlarmARN:
    Value: !GetAtt PnNotificationCostToUpdateQueue.Outputs.SqsAgeAlarmArn
    Description: pn-Notification-Cost-To-Update age alarm ARN