AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  #Log
  LogRetention:
    Type: Number
    Default: 14
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  #DynamoDB tables
  NotificationDeliveryCostTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-NotificationDeliveryCost'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  #Log Group
  PnNotificationCostServiceLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-notification-cost-service'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

Outputs:
  # DynamoDB tables
  NotificationDeliveryCostTableName:
    Description: Name of dynamodb table containing cost of notification delivery
    Value: !Ref NotificationDeliveryCostTable
  
  NotificationDeliveryCostTableArn:
    Description: ARN of dynamodb table containing cost of notification delivery
    Value: !Sub '${NotificationDeliveryCostTable.Arn}'
  # Log group exports
  EcsNotificationCostServiceLogGroup:
    Value: !GetAtt PnNotificationCostServiceLogGroup.Outputs.LogGroupName