package it.pagopa.pn.notificationcostservice.exception;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class PnNotificationCostServiceExceptionCodes extends PnExceptionsCodes {
    public static final String ERROR_CODE_NOTIFICATIONDELIVERYCOST_NOTFOUND = "PN_NOTIFICATIONDELIVERYCOST_NOTFOUND";
    public static final String ERROR_CODE_NOTIFICATIONDELIVERYCOST_DELETED = "PN_NOTIFICATIONDELIVERYCOST_DELETED";
    public static final String ERROR_CODE_NOTIFICATIONCOSTSERVICE_DOMAINOBJECTVALIDATION = "PN_NOTIFICATIONCOSTSERVICE_DOMAINOBJECTVALIDATION";
    public static final String ERROR_CODE_NOTIFICATIONCOSTSERVICE_HANDLE_EVENT_FAILED = "PN_NOTIFICATIONCOSTSERVICE_HANDLE_EVENT_FAILED";
    public static final String ERROR_CODE_NOTIFICATIONCOSTSERVICE_ROUTER_EVENT_TYPE_MISSING = "PN_NOTIFICATIONCOSTSERVICE_ROUTER_EVENT_TYPE_MISSING";
    public static final String ERROR_CODE_NOTIFICATIONCOSTSERVICE_INTERNAL_SERVER_ERROR = "PN_NOTIFICATIONCOSTSERVICE_INTERNAL_SERVER_ERROR";
}
