logging.config=config/logback-local.xml

server.port=8093
cors.allowed.domains=http://localhost:8090,http://localhost:8091

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

#DynamoDb table name
pn.notification-cost-service.notification-delivery-cost-table.table-name=pn-NotificationDeliveryCost
pn.notification-cost-service.payment-info-table.table-name=pn-PaymentInfo

pn.notification-cost-service.sendFee=100

# Queue inbound event configuration
pn.notification-cost-service.topics.pn-notification-cost-to-update=pn-notification-cost-to-update


#EVENTBUS
pn.notification-cost-service.event-bus.name=pn-CoreEventBus
pn.notification-cost-service.event-bus.source=pn-notification-cost-service
pn.notification-cost-service.event-bus.outcome-event-detail-type=NotificationCostServiceOutcomeEvent

#Feature Flags
pn.notification-cost-service.new-actualization-cost-for-async=2026-05-30T00:00:00Z