logging.config=config/logback-local.xml

server.port=8093
cors.allowed.domains=http://localhost:8090,http://localhost:8091

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

#DynamoDb table name
pn.notification-cost-service.notification-delivery-cost-table.table-name=NotificationDeliveryCost